title: QMK Configurator
email: hello@qmk.fm
show_downloads: true
description: QMK for potatoes - an open source configurator for QMK Firmware (only the AVR boards right now)
baseurl: ""
url: "http://config.qmk.fm"
github_username: qmk
repository: qmk/qmk_configurator
theme: jekyll-theme-minimal
